---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: clapclapexcitement/dcind-ansible-molecule

inputs:
  - name: ansible-hello-world

run:
  dir: ansible-hello-world
  path: molecule
  args:
    - test
